version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Build from the backend folder
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend  # Build from the frontend folder
    ports:
      - "80:80"
